### ISSUE TITLE
The validation is incomplete

### ISSUE THREAD

**Issue by winklerj** [leighs-hammer/shopify-jwt-auth-verify#2]
There are additional steps to fully validate the JWT according to the Shopify documentation here: https://shopify.dev/tutorials/authenticate-your-app-using-session-tokens#obtain-session-details-manually.  Steps 3-6 are missing. I used the callback function to add in the steps.  It would be nice if the callback result was returned instead of true.

Here is my callback which implements steps 3-5

```
            // Validate the JWT shop matches the session cookie
            let extraValidation = true;
            const validJWT = isVerified(headers.authorization, process.env.SHOPIFY_API_SECRET, (authObject) => {
                const payload = JSON.parse(authObject.payload);
                const time = new Date().getTime() / 1000;
                const isAfter = payload.nbf <= time;
              
                if(!isAfter) {
                  console.error('Token is not yet valid');
                  extraValidation = false;
                }
                const iss = new URL(payload.iss).hostname;
                const dest = new URL(payload.dest).hostname;
                if(iss != dest) {
                    console.error(`Token issuer ${iss} does not match the destination ${dest}`);
                    extraValidation = false;
                } else if(payload.aud != process.env.SHOPIFY_API_KEY) {
                    console.error('Token does not match the Shopify API Key');
                    extraValidation = false;
                }
                return extraValidation;
            });
// Check validJWT and extraValidation

```

**Comment by leighs-hammer** [comment]
Those additional fields did not exist when this was written good point I will look at carving some time to dig into what has been added or changed since beta and initial launch. thanks for the heads up @winklerj

**Comment by leighs-hammer** [comment]
Hey @winklerj added the core logic directly internally, as well as adjusted the callback to have an option to return the response/return of the callback. Details of V2 are here, pre trialing

https://github.com/leighs-hammer/shopify-jwt-auth-verify/pull/8

I need to trial this in a number of live apps where the logic was external and give people a heads up but this should go out this week.

**Comment by winklerj** [comment]
It might be a couple weeks before I can test this out, but I'm interested in using the updated version.  I appreciate you putting in the time for this change.
